### ISSUE TITLE
Site content is too wide on iOS 

### ISSUE THREAD

**Issue by mustafa-x** [PWA-Summit/2021.pwasummit.org#20]
The content on session pages seem larger then the width of the screen and there is horizontal scrolling. 

This was observed on Chrome and Safari
![A2408A65-C8BB-4E46-B869-6A9FAED7DF23](https://user-images.githubusercontent.com/1212513/129789973-9dab08b4-49be-498e-b507-c955c3056adc.png)
![0F052175-E4A9-4847-8FF5-97E85B665F17](https://user-images.githubusercontent.com/1212513/129789983-9b135071-0395-4a54-90bd-f07dd5d6b49a.png)

**Comment by Snugug** [comment]
Thanks, working on it now.
