### ISSUE TITLE
Content package for the landing page

### ISSUE THREAD

**Issue by webmaxru** [PWA-Summit/2021.pwasummit.org#3]
For the very first version of the website (we can call it a Landing Page) I suggest to have following content pieces:

- Logo (graphic)
- Conference name
- Date and location (October 7, online)
- Slogan
- 1-2 paragraphs of the general description
- Organizers (1 paragraph)
- Call to action 1: reserve a date (calendar invitation)
- Call to action 2: submit a talk (link + a paragraph of description)
- Code of conduct (link + page)
- Copyright, made by, hosted by

**Comment by aarongustafson** [comment]
Thanks for this Maxim! I have incorporated this into the Website Content Plan.
