### ISSUE TITLE
CFP Page content

### ISSUE THREAD

**Issue by webmaxru** [PWA-Summit/2021.pwasummit.org#5]
_HEADER_

# PWA Summit
### October 6-7, Online

_HERO_

[🎤 Be a speaker](url)
[📅 Reserve a date](url)

_MAIN_

# What is PWA Summit?

PWA Summit 2021 is a two-days single-track conference dedicated to all sides and colors of Progressive Web Apps. Each talk will consist of a 20 minute pre-recorded session and a live Q&A session following the talk. We're looking to draw an audience of web developers and decision makers who are interested in building and deploying Progressive Web Apps.

# Why to attend

## Learn

Learn everything about Progressive Web Apps, including development tips, tooling, libraries, debugging to browser support and business cases.

## Meet

Meet a diverse set of speakers from the PWA ecosystem representing multiple roles, skills, and experience levels.

## Build

After the Summit, you will have all the knowledge and skills to build or improve your web application

## Join

Join a huge community of like-minded developers in the interactive parts of PWA Summit

# Why to speak

* Share your findings, thoughts, experience with PWA in front of the thousands of the developers interested in this topic
* Selected speakers will be provided with recording guidance and support
* We will offer presentation coaching for any speaker who would like it
* New speakers are not only welcome, but encouraged to apply!
* An honorarium will be offered to all selected speakers wherever local regulations allow

# Organizing team

* Person 1
* Person 2
* ...

# Sponsors

* Google
* Microsoft
* Intel
* Samsung Internet
* Netlify

_FOOTER_

# © 2021 PWA Summit Team

* Code of Conduct
* @PWASummit Twitter
* Contact Us

**Comment by webmaxru** [comment]
Cool! Thanks for the great work, Sam! Is there dev build deployed to see changes in action?

**Comment by Snugug** [comment]
> Cool! Thanks for the great work, Sam! Is there dev build deployed to see changes in action?

Yup! PR's [here](https://github.com/PWA-Summit/2021.pwasummit.org/pull/4) and one of the checks is a deploy preview, which right now is available [here](https://deploy-preview-4--peaceful-darwin-86c101.netlify.app/)

**Comment by aarongustafson** [comment]
How’s this for a one-sentence blurb?

> A single-track conference focused on helping everyone succeed with Progressive Web Apps.

I tried to boil down all of the details into broader text that we can expound upon in the "about" page.

**Comment by Snugug** [comment]
I think that's great, thanks Aaron. I added "free, online" in front of "single-track" as it looks like that wasn't included anywhere
